### ISSUE TITLE
Add missing Sonar Analysis in GitHub Actions

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite-extension#24]
Should be similar to JHLite

TO-DO

- [x] add local sonar analysis which doesn't need an environment token (https://github.com/jhipster/jhipster-lite-extension/pull/32)
- [x] add sonar cloud token environment variable at [this project settings](https://github.com/jhipster/jhipster-lite-extension/settings/secrets/actions) 
- [ ] add sonar cloud analysis which uses the `SONAR_TOKEN`

**Comment by renanfranca** [comment]
> add sonar cloud token environment variable at this project settings

@pascalgrimaud : when you have the time, can you help me with this task?

**Comment by pascalgrimaud** [comment]
Yes will do it and I'll answer here when it's done

**Comment by pascalgrimaud** [comment]
done:
- just created the project at sonarcloud
- added the SONAR_TOKEN in this project

![image](https://github.com/user-attachments/assets/71142004-8a1c-4ca9-bb4e-0f073ba8827f)

**Comment by pascalgrimaud** [comment]
the id is: `jhipster_jhipster-lite-extension`

**Comment by renanfranca** [comment]
Thanks @pascalgrimaud ! I will work on this tomorrow 😃👍
