### ISSUE TITLE
Update all config

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite-extension#5]
Choosing the default options like com.mycompany etc, are not good
It should be discussed and changed

**Comment by renanfranca** [comment]
@pascalgrimaud : could it be `tech.jhipster.lite.extension`?

**Comment by pascalgrimaud** [comment]
Why not, need to find a project name too
And waiting @murdos 's idea too

**Comment by murdos** [comment]
How about `tech.jhipster.lite.extensions`? 
Unless we only plan to host one extension module (the banner one), using plurals seem to be a good idea.

**Comment by renanfranca** [comment]
> How about `tech.jhipster.lite.extensions`? 
> Unless we only plan to host one extension module (the banner one), using plurals seem to be a good idea.

It could be a place to let contributors create modules that don't fit in the jhipster-lite. Does it sounds good?

**Comment by renanfranca** [comment]
So, it could be:

PackageName
tech.jhipster.lite.extensions

Project Name
JHlite Extensions Application

Base Name
jhliteExtensionsApplication

Let me know, WDYT 😃👍

**Comment by pascalgrimaud** [comment]
No, I don't want additional modules here, I want this project as sample to create a custom jhlite, that's all

**Comment by renanfranca** [comment]
> No, I don't want additional modules here, I want this project as sample to create a custom jhlite, that's all

So the singular is the better choice here:

PackageName
tech.jhipster.lite.extension

Project Name
JHlite Extension Application

Base Name
jhliteExtensionApplication

WDYT?

**Comment by pascalgrimaud** [comment]
Base name: jhliteExtension would be enough

**Comment by pascalgrimaud** [comment]
Project name: JHLite Extension Application (L in upper case)

**Comment by renanfranca** [comment]
Thanks 👍

**Comment by murdos** [comment]
> No, I don't want additional modules here, I want this project as sample to create a custom jhlite, that's all

Fine. Then I guess we should include the word "sample" somewhere.
E.g. in the description: "JHLite Sample Extension Application".

**Comment by pascalgrimaud** [comment]
I think application should reserved to real generated app.

What about :
- JHLite Sample Extension
- JHLite Sample Extension Engine
- JHLite Sample Engine

Another idea?

**Comment by renanfranca** [comment]
I think it could be JHLite Extension Sample

**Comment by pascalgrimaud** [comment]
To resume:

PackageName
tech.jhipster.lite.extension

Project Name
JHLite Extension Sample

Base Name
JHLiteExtensionSample
